services:
  - type: web
    name: find-lawyer
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: find-lawyer-db
          property: connectionString

databases:
  - name: find-lawyer-db
    plan: free
    ipAllowList: [] 